#!/usr/bin/env bash

echo "Installing starship"
# This currently requires confirmation - that blocks Codespaces from properly installing it.
# curl -fsSL https://starship.rs/install.sh | bash

echo "Installing vscode extensions"
./.vscode/install-extensions