#!/usr/bin/env bash

set -e

echo "==> Adding symlinks .config"
cp -r --symbolic-link ./* ~

echo "==> Installing Homebrew"
CI=1 su -c '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"' vscode
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
brew bundle
