#!/usr/bin/env bash

set -e

echo "==> Adding symlinks"
cp -r --symbolic-link /workspaces/.codespaces/.persistedshare/dotfiles/* ~
cp -r --symbolic-link /workspaces/.codespaces/.persistedshare/dotfiles/.config/* ~/.config

echo "==> Installing Homebrew"
CI=1 su -c '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"' vscode
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
brew bundle
